break instead of fallthrough
clang is angry with the fallthrough
> error: fallthrough annotation does not directly precede switch label

break achieves the same